FROM node:latest

WORKDIR /cvme

ARG REACT_APP_GITHUB_ACCESS_TOKEN
ARG REACT_APP_GITHUB_APP_CLIENT_ID
ARG REACT_APP_REDIRECT_URL

ENV REACT_APP_GITHUB_ACCESS_TOKEN ${REACT_APP_GITHUB_ACCESS_TOKEN}
ENV REACT_APP_GITHUB_APP_CLIENT_ID ${REACT_APP_GITHUB_APP_CLIENT_ID}
ENV REACT_APP_REDIRECT_URL ${REACT_APP_REDIRECT_URL}

RUN git clone https://github.com/alexalexyang/cvme /cvme
RUN npm install && npm install --only=dev